url: https://joelebers.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Joel Ebers
email: joelebers1@gmail.com
description: "Mechanical Engineer"
#"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
#people:
#- name: Kay Garland
#  pic: 1
#  position: Lead Designer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/joelebers/
  - title: github
    url: http://joelebers.github.io

# Build settings
markdown: kramdown
permalink: pretty
